apiVersion: v1
kind: ConfigMap
metadata:
  name: traefik-chart-values
  namespace: kube-system
data:
  values-0-000-HelmChart-ValuesContent.yaml: |
    providers:
      kubernetesCRD:
        enabled: true
      kubernetesIngress:
        enabled: true

    additionalArguments:
      - "--providers.kubernetescrd"
      - "--providers.kubernetescrd.allowEmptyServices=true"
      - "--providers.kubernetesingress=true"
