apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: backend-ingress
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-cors-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - api.ptit-boot-checkin.site
      secretName: backend-tls-cert
  rules:
    - host: api.ptit-boot-checkin.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: backend
                port:
                  number: 3456
