apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: chatbot-ingress
  namespace: apps
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-production
    traefik.ingress.kubernetes.io/router.entrypoints: web,websecure
    traefik.ingress.kubernetes.io/router.middlewares: default-cors-headers@kubernetescrd
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - chatbot.ptit-boot-checkin.site
      secretName: chatbot-tls-cert
  rules:
    - host: chatbot.ptit-boot-checkin.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: chatbot
                port:
                  number: 5000
