apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - argocd-ingress.yaml
  - argocd-tls-option.yaml
  - be-ingress.yaml
  - traefik-cors-middleware.yaml
  - grafana-ingress.yaml
  - db-ingress.yaml
  - chatbot-ingress.yaml
